#define MyAppName "Backup Compressor"
#define MyAppVersion "3.1.1"
#define MyAppPublisher "V"
#define MyAppExeName "Backup Compressor.exe"

[Setup]
AppId={{D37BB4F5-42C4-4C6B-91C7-BACKUPCOMPRESSOR}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
OutputDir=installer_output
OutputBaseFilename=Backup Compressor Setup 3.1.1
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=app_icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
CloseApplications=yes
RestartApplications=no
RestartIfNeededByRun=no

[Files]
Source: "dist\Backup Compressor.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "installer_files\7z.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall


[Icons]
Name: "{group}\Backup Compressor"; Filename: "{app}\Backup Compressor.exe"; IconFilename: "{app}\Backup Compressor.exe"
Name: "{commondesktop}\Backup Compressor"; Filename: "{app}\Backup Compressor.exe"; IconFilename: "{app}\Backup Compressor.exe"

[Run]
Filename: "{tmp}\7z.exe"; Parameters: "/S"; StatusMsg: "Installing 7-Zip..."; Flags: waituntilterminated; Check: not Is7ZipInstalled
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent runascurrentuser


; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Code]

const
  PreviousUninstallKey = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{D37BB4F5-42C4-4C6B-91C7-BACKUPCOMPRESSOR}_is1';

function GetPreviousUninstallString(var UninstallString: String): Boolean;
begin
  Result := True;

  if RegQueryStringValue(HKLM, PreviousUninstallKey, 'UninstallString', UninstallString) then
    Exit;

  if RegQueryStringValue(HKCU, PreviousUninstallKey, 'UninstallString', UninstallString) then
    Exit;

  Result := False;
end;

function GetUninstallExe(UninstallString: String): String;
var
  EndQuotePos: Integer;
  UninstallCommand: String;
begin
  UninstallCommand := UninstallString;

  if Copy(UninstallCommand, 1, 1) = '"' then
  begin
    UninstallCommand := Copy(UninstallCommand, 2, Length(UninstallCommand) - 1);
    EndQuotePos := Pos('"', UninstallCommand);

    if EndQuotePos > 0 then
      Result := Copy(UninstallCommand, 1, EndQuotePos - 1)
    else
      Result := UninstallCommand;
  end
  else
    Result := UninstallCommand;
end;

function RunPreviousUninstaller(UninstallString: String): Boolean;
var
  ResultCode: Integer;
  UninstallExe: String;
begin
  UninstallExe := GetUninstallExe(UninstallString);

  if not FileExists(UninstallExe) then
  begin
    Result := False;
    Exit;
  end;

  if not Exec(
    UninstallExe,
    '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART',
    '',
    SW_HIDE,
    ewWaitUntilTerminated,
    ResultCode
  ) then
  begin
    Result := False;
    Exit;
  end;

  Result := ResultCode = 0;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  UninstallString: String;
begin
  Result := '';

  if GetPreviousUninstallString(UninstallString) then
  begin
    if not RunPreviousUninstaller(UninstallString) then
      Result := 'Setup could not uninstall the existing {#MyAppName} installation. Please uninstall it manually and run Setup again.';
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    if not FileExists(ExpandConstant('{pf}\WinRAR\Rar.exe')) then
    begin
      MsgBox(
        'RAR compression requires WinRAR to be installed separately.' + #13#10 + #13#10 +
        'Download WinRAR from:' + #13#10 +
        'https://www.win-rar.com/',
        mbInformation,
        MB_OK
      );
    end;
  end;
end;


function Is7ZipInstalled(): Boolean;
begin
  Result :=
    FileExists(ExpandConstant('{pf}\7-Zip\7z.exe')) or
    FileExists(ExpandConstant('{pf32}\7-Zip\7z.exe'));
end;
